.PHONY: clean All

All:
	@echo "----------Building project:[ EjercicioPropuesto1 - Debug ]----------"
	@cd "EjercicioPropuesto1" && "$(MAKE)" -f  "EjercicioPropuesto1.mk"
clean:
	@echo "----------Cleaning project:[ EjercicioPropuesto1 - Debug ]----------"
	@cd "EjercicioPropuesto1" && "$(MAKE)" -f  "EjercicioPropuesto1.mk" clean
